name: CD for main Branch

on:
  workflow_run :
    workflows : ['CI for dev Branch']
    types : 
      - completed
      

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for backend
      - name: Set up Node.js (backend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies and run backend tests
      - name: Install backend dependencies and run tests
        working-directory: backend
        run: |
          npm install
          npm test

      # Step 4: Set up Node.js for frontend
      - name: Set up Node.js (frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 5: Install dependencies and run frontend tests
      - name: Install frontend dependencies and run tests
        working-directory: frontend
        run: |
          npm install
          npm test

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build and push Docker images for backend
      - name: Build and push backend Docker image
        working-directory: backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # Step 8: Build and push Docker images for frontend
      - name: Build and push frontend Docker image
        working-directory: frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
