#Test

name: CI for dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for backend
      - name: Set up Node.js (backend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies and run backend tests
      - name: Install backend dependencies and run tests
        working-directory: backend
        run: |
          npm install
          npm test

      # Step 4: Set up Node.js for frontend
      - name: Set up Node.js (frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 5: Install dependencies and run frontend tests
      - name: Install frontend dependencies and run tests
        working-directory: frontend
        run: |
          npm install
          npm test

      # Step 6: Merge dev into main if tests are successful
      - name: Merge dev into main
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout main
          git merge dev
          git push origin main
